### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by Masynka** [ChimesOfDestruction/njRAT-0.7d-Platinum-Edition#1]
This program doesn't work with ngrok(in other njrat workes)

**Comment by ChimesOfDestruction** [comment]
Working on my end friend, add some more details about the problem.
It's working through pastebin DNS and normal DNS for me.
![test](https://user-images.githubusercontent.com/127018596/229312153-f923318d-8274-4635-875e-ea483b75b8bb.PNG)

**Comment by Masynka** [comment]
Sorry,this is my bad

**Comment by ChimesOfDestruction** [comment]
No problem friend. 👍👍👍

**Comment by Masynka** [comment]
If u choose pastebin and later remove he will remain

**Comment by ChimesOfDestruction** [comment]
Pastebin checks on every time the RAT is started, for example:
Victim starts trojan, it checks pastebin and connects, but it never rechecks while its connected.
After victim restarts PC it checks pastebin again. So you cannot update pastebin live.
